export const USERS_MESSAGES = {
  VALIDATION_ERROR: 'Lỗi xác nhận',
  NAME_IS_REQUIRED: 'Tên là bắt buộc',
  NAME_MUST_BE_A_STRING: 'Tên phải là một chuỗi',
  NAME_LENGTH_MUST_BE_FROM_1_TO_100: 'ĐỘ DÀI TÊN PHẢI TỪ 1 ĐẾN 100',
  EMAIL_ALREADY_EXSTS: 'EMAIL đã tồn tại',
  EMAIL_IS_REQUIREA: 'EMAIL LÀ YÊU CẦU',
  EMAIL_IS_INVALID: 'EMAIL KHÔNG HỢP LỆ',
  USERS_NOT_FOUND: 'Không tìm thấy USERS',
  USERS_OR_PASSWORD_IS_INCORRECT: 'EMAIL OR PASSWORD KHÔNG HỢP LỆ',
  PASSWORD_IS_REQUIREA: 'PASSWORD LÀ YÊU CẦU',
  PASSWORD_MUST_BE_A_STRING: 'MẬT KHẨU PHẢI LÀ MỘT CHUỖI',
  PASSWORD_LENGTH_MUST_FROM_6_TO_50: 'ĐỘ DÀI MẬT KHẨU PHẢI TỪ 6 ĐẾN 50',
  PASSWORD_MUST_BE_A_STRONG: 'MẬT KHẨU PHẢI dài từ 6-50 ký tự và chứa ít nhất 1 chữ cái thường, 1 chữ cái in hoa, 1 chữ số, 1 ký hiệu',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Yêu cầu xác nhận mật khẩu',
  CONFIRM_PASSWORD_MUST_BE_A_STRING: 'Xác nhận mật khẩu phải là một chuỗi',
  CONFIRM_PASSWORD_LENGTH_MUST_BE_FROM_6_TO_50: 'Độ dài mật khẩu xác nhận phải từ 6 đến 50',
  CONFIRM_PASSWORD_MUST_BE_STRONG: 'Xác nhận mật khẩu phải dài từ 6-50 ký tự và chứa ít nhất 1 chữ cái thường, 1 chữ cái viết hoa, 1 số và 1 ký hiệu',
  CONFIRM_PASSWORD_MUST_BE_THE_SAME_AS_PASSWORD: 'Xác nhận mật khẩu nhập lại không khớp với mật khẩu ban đầu',
  DATE_OF_BIRTH_MUST_BE_IS08601: 'Ngày sinh phải là IS08601',
  LOGIN_SUCCESS: 'Login thành công',
  REGISTER_SUCCESS: 'Register thành công',
  ACCESS_TOKEN_IS_INVALID: 'ACCESS TOKEN  KHÔNG HỢP LỆ',
  ACCESS_TOKEN_IS_REQUIRED: 'MÃ TRUY CẬP  ACCESS_TOKEN LÀ BẮT BUỘC',
  REFRESH_TOKEN_IS_REQUIRED:'MÃ TRUY CẬP REFRESH_TOKEN LÀ BẮT BUỘC',
  LOGOUT_SUCCESS: 'ĐĂNG XUẤT THÀNH CÔNG',
  USED_REFRESH_TOKEN_OR_NOT_EXIST: 'ĐÃ SỬ DỤNG REFRESH TOKEN HOẶC KHÔNG TỒN TẠI',
  INVALID_TOKEN : 'MÃ THÔNG BÁO KHÔNG HỢP LỆ',
  SEARCH_FOR_SUCCESS :'TIM KIẾM THÀNH CÔNG'
} as const
